import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState
} from 'react';
import Color from 'color';
import { Button, Flex, Stack, Text } from '@sanity/ui';
import { set, setIfMissing } from 'sanity';
import { resolveThemeDefinition } from '@/lib/themes';

const ThemeStyleContext = createContext(null);

const COLOR_FIELDS = [
  { key: 'primary', field: 'primaryColor' },
  { key: 'secondary', field: 'secondaryColor' },
  { key: 'background', field: 'backgroundColor' },
  { key: 'text', field: 'textColor' }
];

function getStyleImageUrl(value) {
  return (
    value?.image?.derived?.[0]?.secure_url || value?.image?.secure_url || null
  );
}

function toFiniteNumber(value) {
  return Number.isFinite(value) ? value : 0;
}

function createColorValue(hex) {
  const color = Color(hex);
  const normalizedHex = color.hex();
  const rgb = color.rgb().object();
  const hsl = color.hsl().object();
  const hsv = color.hsv().object();

  return {
    _type: 'color',
    hex: normalizedHex,
    alpha: 1,
    hsl: {
      _type: 'hslaColor',
      h: toFiniteNumber(hsl.h),
      s: toFiniteNumber(hsl.s) / 100,
      l: toFiniteNumber(hsl.l) / 100,
      a: 1
    },
    hsv: {
      _type: 'hsvaColor',
      h: toFiniteNumber(hsv.h),
      s: toFiniteNumber(hsv.s) / 100,
      v: toFiniteNumber(hsv.v) / 100,
      a: 1
    },
    rgb: {
      _type: 'rgbaColor',
      r: Math.round(toFiniteNumber(rgb.r)),
      g: Math.round(toFiniteNumber(rgb.g)),
      b: Math.round(toFiniteNumber(rgb.b)),
      a: 1
    }
  };
}

function getMissingColorFields(value) {
  return COLOR_FIELDS.filter(({ field }) => !value?.[field]?.hex);
}

function getGeneratedColorPatches(colors, fields, schemaTypeName) {
  const patches = fields
    .map(({ field, key }) => {
      const color = colors?.[key];

      return color ? set(createColorValue(color), [field]) : null;
    })
    .filter(Boolean);

  return patches.length > 0
    ? [setIfMissing({ _type: schemaTypeName }), ...patches]
    : [];
}

export function ThemeStyleInput(props) {
  const { onChange, renderDefault, readOnly, schemaType, value } = props;
  const [status, setStatus] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const hasMountedRef = useRef(false);
  const latestValueRef = useRef(value);
  const previousImageUrlRef = useRef(null);
  const autoGeneratedImageUrlRef = useRef(null);
  const imageUrl = useMemo(() => getStyleImageUrl(value), [value]);
  const missingColorFields = useMemo(
    () => getMissingColorFields(value),
    [value]
  );
  const missingColorCount = missingColorFields.length;

  useEffect(() => {
    latestValueRef.current = value;
  }, [value]);

  const generateMissingColors = useCallback(
    async ({ automatic = false } = {}) => {
      if (!imageUrl || readOnly || isGenerating || missingColorCount === 0) {
        return;
      }

      setIsGenerating(true);
      setStatus(null);

      try {
        const resolvedTheme = await resolveThemeDefinition({ url: imageUrl });

        if (!resolvedTheme?.colors) {
          throw new Error('No colors were generated for this image.');
        }

        const currentMissingColorFields = missingColorFields.filter(
          ({ field }) => !latestValueRef.current?.[field]?.hex
        );

        const patches = getGeneratedColorPatches(
          resolvedTheme.colors,
          currentMissingColorFields,
          schemaType.name
        );

        if (patches.length === 0) {
          return;
        }

        onChange(patches);

        setStatus({
          tone: 'positive',
          text: automatic
            ? `Auto-generated ${currentMissingColorFields.length} missing theme color${currentMissingColorFields.length === 1 ? '' : 's'}.`
            : `Generated ${currentMissingColorFields.length} missing theme color${currentMissingColorFields.length === 1 ? '' : 's'}.`
        });
      } catch (error) {
        console.error('Error generating theme colors in Sanity Studio:', error);
        setStatus({
          tone: 'critical',
          text: 'Could not generate colors from this image.'
        });
      } finally {
        setIsGenerating(false);
      }
    },
    [
      imageUrl,
      isGenerating,
      missingColorCount,
      missingColorFields,
      onChange,
      readOnly,
      schemaType.name
    ]
  );

  useEffect(() => {
    if (!hasMountedRef.current) {
      hasMountedRef.current = true;
      previousImageUrlRef.current = imageUrl;
      return;
    }

    const previousImageUrl = previousImageUrlRef.current;
    previousImageUrlRef.current = imageUrl;

    if (
      !imageUrl ||
      imageUrl === previousImageUrl ||
      imageUrl === autoGeneratedImageUrlRef.current ||
      readOnly ||
      isGenerating ||
      missingColorCount === 0
    ) {
      return;
    }

    autoGeneratedImageUrlRef.current = imageUrl;
    generateMissingColors({ automatic: true });
  }, [
    generateMissingColors,
    imageUrl,
    isGenerating,
    missingColorCount,
    readOnly
  ]);

  return (
    <ThemeStyleContext.Provider
      value={{
        generateMissingColors,
        imageUrl,
        isGenerating,
        missingColorCount,
        readOnly,
        status
      }}>
      {renderDefault(props)}
    </ThemeStyleContext.Provider>
  );
}

export function ThemeColorGeneratorInput() {
  const themeStyle = useContext(ThemeStyleContext);

  if (!themeStyle) {
    return null;
  }

  const {
    generateMissingColors,
    imageUrl,
    isGenerating,
    missingColorCount,
    readOnly,
    status
  } = themeStyle;

  return (
    <Stack space={2}>
      <Flex align='center' gap={2} wrap='wrap'>
        <Button
          text='Generate missing'
          mode='ghost'
          tone='primary'
          fontSize={1}
          padding={2}
          disabled={
            !imageUrl || readOnly || isGenerating || missingColorCount === 0
          }
          loading={isGenerating}
          onClick={() => generateMissingColors()}
        />

        <Text size={0} muted>
          Fills blanks from the image.
        </Text>
      </Flex>

      {!imageUrl && (
        <Text size={0} muted>
          Add an image first.
        </Text>
      )}

      {status && (
        <Text size={0} tone={status.tone}>
          {status.text}
        </Text>
      )}

      {imageUrl && missingColorCount === 0 && !status && (
        <Text size={0} muted>
          All colours are set.
        </Text>
      )}
    </Stack>
  );
}
