import {
  LuBox,
  LuCamera,
  LuCheck,
  LuCode,
  LuDatabase,
  LuFlaskConical,
  LuFrame,
  LuGauge,
  LuGlobe,
  LuHammer,
  LuLayers,
  LuLightbulb,
  LuMessageCircle,
  LuMonitor,
  LuPalette,
  LuPenTool,
  LuRocket,
  LuSearch,
  LuShieldCheck,
  LuSmartphone,
  LuSparkles,
  LuTerminal,
  LuUsers,
  LuZap
} from 'react-icons/lu';

// The Studio offers exactly these names, so every stored icon has a glyph.
export const creativeIcons = {
  box: LuBox,
  camera: LuCamera,
  check: LuCheck,
  code: LuCode,
  database: LuDatabase,
  'flask-conical': LuFlaskConical,
  frame: LuFrame,
  gauge: LuGauge,
  globe: LuGlobe,
  hammer: LuHammer,
  layers: LuLayers,
  lightbulb: LuLightbulb,
  'message-circle': LuMessageCircle,
  monitor: LuMonitor,
  palette: LuPalette,
  'pen-tool': LuPenTool,
  rocket: LuRocket,
  search: LuSearch,
  'shield-check': LuShieldCheck,
  smartphone: LuSmartphone,
  sparkles: LuSparkles,
  terminal: LuTerminal,
  users: LuUsers,
  zap: LuZap
};
