/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { a, useTransition, useSpring, config } from "@react-spring/three";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "https://res.cloudinary.com/ruben-p/image/upload/3D%20Models/Logo/RP-Logo.glb"
  );

  const { transparency } = useSpring({
    config: { mass: 5, tension: 500, friction: 100 },

    to: {
      transparency: 1,
    },
    from: { transparency: 0 },
  });
  return (
    <group {...props} dispose={null}>
      <a.mesh
        castShadow
        receiveShadow
        geometry={nodes["RP_-_Logo001"].geometry}
        material={materials.Abstract}
        material-transparent
        material-opacity={transparency}
      />
    </group>
  );
}

useGLTF.preload(
  "https://res.cloudinary.com/ruben-p/image/upload/3D%20Models/Logo/RP-Logo.glb"
);
