/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 C:\Users\Ruben\Downloads\RP-Logo.glb -T --shadows
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { a, useSpring } from '@react-spring/three';

export function RpLogo(props) {
  const { nodes, materials } = useGLTF(
    'https://res.cloudinary.com/ruben-p/image/upload/v1692730013/3D%20Models/Logo/RP-Logo.glb'
  );

  const { transparency } = useSpring({
    config: { mass: 5, tension: 500, friction: 100 },

    to: {
      transparency: 1
    },
    from: { transparency: 0 }
  });

  const myMesh = React.useRef();

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime() / 3;
    myMesh.current.rotation.y = a;
    let scale = window.screen.width / 600;
    if (scale > 1) {
      scale = 1;
    }
    myMesh.current.scale.set(scale, scale, scale);
  });
  return (
    <group {...props} dispose={null}>
      <a.mesh
        geometry={nodes['RP_-_Logo001'].geometry}
        material={materials.Abstract}
        material-transparent
        material-opacity={transparency}
        ref={myMesh}
        scale={[1, 1, 1]}
      />
    </group>
  );
}

useGLTF.preload(
  'https://res.cloudinary.com/ruben-p/image/upload/v1692730013/3D%20Models/Logo/RP-Logo.glb'
);
