/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 C:\Users\Ruben\Downloads\RP-Logo.glb -T --shadows
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { a, useSpring, config } from "@react-spring/three";

export function Model(props) {
  const { nodes, materials } = useGLTF('https://res.cloudinary.com/ruben-p/image/upload/v1692730013/3D%20Models/Logo/RP-Logo.glb')

  const { transparency } = useSpring({
    config: { mass: 5, tension: 500, friction: 100 },

    to: {
      transparency: 1,
    },
    from: { transparency: 0 },
  });
  return (
    <group {...props} dispose={null}>
      <a.mesh
        geometry={nodes["RP_-_Logo001"].geometry}
        material={materials.Abstract}
        material-transparent
        material-opacity={transparency}
      />
    </group>
  )
}

useGLTF.preload('https://res.cloudinary.com/ruben-p/image/upload/v1692730013/3D%20Models/Logo/RP-Logo.glb')
