import Head from 'next/head'

export default function About() {
  return (
    <page>
      <Head>
        <title>About Ruben</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <hero>
        <h1-image>ABOUT</h1-image>
      </hero>
    </page>
  )
}
