import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact Ruben</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <hero>
        <h1>CONTACT</h1>
      </hero>
    </>
  )
}
