import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <page>
      <Head>
        <title>Ruben P</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <hero>
        <h1-image>Ruben<br />Panzich</h1-image>
      </hero>
    </page>
  )
}
