import React, { Suspense, useState } from 'react'
import { Canvas, useFrame } from '@react-three/fiber'
import { OrbitControls, Environment, Effects, Loader, useTexture } from '@react-three/drei'
import { useSpring, animated, config } from '@react-spring/three'
import Head from 'next/head'
import Model from '../components/RP-Logo'

function Logo() {
  const myMesh = React.useRef();
  const [active, setActive] = useState(false);

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();
    myMesh.current.rotation.y = a;
    console.log(Math.min(window.innerHeight, window.innerWidth));
  });

  const scale = Math.min(window.innerHeight/1007, window.innerWidth/595);

  return (
    <animated.mesh
      ref={myMesh}>
      <Model scale={[scale, scale, scale]}/>
    </animated.mesh>
  );
}

export default function Home() {
  return (
    <page>
      <Head>
        <title>Ruben P</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <hero>
        <layer>
          <Canvas
          colorManagement camera={{ position: [0, 0, 2], fov: 80}}
          style={{width: "90vw", height: "90vh"}}>
          <pointLight position={[0, 0, 1]} />
          <ambientLight intensity={0.5} />
            <Suspense fallback={null}>
                  <Logo />
            </Suspense>
          </Canvas>
        </layer>
        <layer>
          <h1-image>Ruben<br />Panzich</h1-image>
        </layer>
      </hero>
    </page>
  )
}
