import { Suspense } from 'react'
import { Canvas } from '@react-three/fiber'
import { OrbitControls, Environment, Effects, Loader, useTexture } from '@react-three/drei'
import Head from 'next/head'
import Model from '../components/RP-Logo'

export default function Tester() {
  return (
    <page>
      <Head>
        <title>Ruben P</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <hero>
        <layer>
          <Canvas 
          colorManagement camera={{ position: [0, 0, 2], fov: 80}}
          style={{width: "90vw", height: "90vh"}}
          frameloop="demand">
          <pointLight position={[0, 0, 1]} />
            <Suspense fallback={null}>
              <Model scale={[1, 1, 1]}/>
            </Suspense>
          </Canvas>
        </layer>
        <layer>
          <h1-image>Model</h1-image>
        </layer>
      </hero>
      <Loader />
    </page>
  )
}
